spring:
  application:
    name: articleserver
  profiles:
    active: default
  config:
    import: configserver:http://localhost:8888
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
    instance:
      instance-id: ${spring.application.name}:${random.value}
      prefer-ip-address: true

#  jpa:
#    hibernate:
#      ddl-auto: update
#  datasource:
#    url: jdbc:mariadb://sks.db.dergeorg.at:3307/sks
#    username: sksuser
#    password: sksuserpw
#    driver-class-name: org.mariadb.jdbc.Driver
#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: myGroup
#encrypt:
#  key: sksuserpw
