server:
  port: 8051

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mariadb://sks.db.dergeorg.at:3307/sks
    username: sksuser
    password: sksuserpw
    driver-class-name: org.mariadb.jdbc.Driver
